import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Sidebar } from "../_navigation/sidebar/components/sidebar";
import { Header } from "../_navigation/header";
import { Toaster } from "@/components/toaster";
import { LocalMessageProvider } from "@/components/i18n/local-message-provider";
import { Locale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,	
	params
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: Locale }>;
}>) {
	const { locale } = await params;
	// 验证 locale 是否有效
	if (!routing.locales.includes(locale as typeof routing.locales[number])) {
		notFound();
	}
	// 设置请求的 locale，这样 getRequestConfig 中的 requestLocale 就能正确获取
	setRequestLocale(locale);
	
	const messages = await getMessages();
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider>
					<LocalMessageProvider locale={locale} messages={messages}>
						<Header />
						<div className="flex h-screen overflow-hidden border-collapse">
							<Sidebar />
							<main
								className="
              min-h-screen flex-1
              overflow-y-auto overflow-x-hidden
              py-24 px-8
              bg-secondary/20
              flex flex-col
              "
							>
								{children}
							</main>
						</div>
						<Toaster expand />
					</LocalMessageProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
