import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Sidebar } from "../_navigation/sidebar/components/sidebar";
import { Header } from "../_navigation/header";
import { LayoutBreadcrumb } from "../_navigation/layout-breadcrumb";
import { PixelCanvasBackground } from "@/components/ui/pixel-canvas-background";
import { Toaster } from "@/components/toaster";
import { LocalMessageProvider } from "@/components/i18n/local-message-provider";
import { Locale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import localFont from "next/font/local";

const geelyDesign = localFont({
	src: "../../../public/fonts/GeelyDesignType-B.ttf",
	variable: "--font-geely-design",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,	
	params
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: Locale }>;
}>) {
	const { locale } = await params;
	// 验证 locale 是否有效
	if (!routing.locales.includes(locale as typeof routing.locales[number])) {
		notFound();
	}
	// 设置请求的 locale，这样 getRequestConfig 中的 requestLocale 就能正确获取
	setRequestLocale(locale);
	
	const messages = await getMessages({locale});

	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} ${geelyDesign.variable} antialiased flex h-screen flex-col overflow-hidden bg-transparent`}>
				<NuqsAdapter>
					<ThemeProvider>
						<LocalMessageProvider locale={locale} messages={messages}>
						<PixelCanvasBackground
							colors={["var(--primary)", "var(--chart-1)", "var(--chart-2)"]}
							gap={500}
							speed={50}
						/>
						<div className="shrink-0">
							<Header />
						</div>
						<div className="relative z-10 flex min-h-0 flex-1 overflow-hidden border-collapse">
							<Sidebar />
							<main
								className="
              flex min-h-0 flex-1 flex-col
              overflow-y-auto overflow-x-hidden
              scrollbar-hide
              py-24 px-8
              bg-secondary/20
              "
							>
								<LayoutBreadcrumb />
								{children}
							</main>
						</div>
						<Toaster expand />
						</LocalMessageProvider>
					</ThemeProvider>
				</NuqsAdapter>
			</body>
		</html>
	);
}
